# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'global_s.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Global(object):
    def setupUi(self, Global):
        Global.setObjectName("Global")
        Global.resize(426, 310)
        font = QtGui.QFont()
        font.setFamily("黑体")
        Global.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/图标.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Global.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Global)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Global)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.listView = QtWidgets.QListView(Global)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(Global)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Global)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Global)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border-radius: 10px; /* 设置圆角半径 */\n"
"    font-family: \'Microsoft YaHei\'; /* 设置字体为微软雅黑 */\n"
"    font-weight: bold; /* 设置字体加粗 */\n"
"    padding: 3px 5px; /* 设置内边距，使按钮看起来更美观 */\n"
"border: 2px solid transparent; /* 设置边框为透明 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 0); /* 设置鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 85, 127); /* 设置按钮按下时的背景颜色 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Global)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 3, 1, 1)

        self.retranslateUi(Global)
        QtCore.QMetaObject.connectSlotsByName(Global)

    def retranslateUi(self, Global):
        _translate = QtCore.QCoreApplication.translate
        Global.setWindowTitle(_translate("Global", "全局参数"))
        self.label.setText(_translate("Global", "资源文件夹路径：（双击打开路径）"))
        self.pushButton_4.setText(_translate("Global", "上移"))
        self.pushButton_5.setText(_translate("Global", "下移"))
        self.pushButton.setText(_translate("Global", "添加文件夹"))
        self.pushButton_2.setText(_translate("Global", "删除"))
import images_rc
