# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variablepool.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VariablePool(object):
    def setupUi(self, VariablePool):
        VariablePool.setObjectName("VariablePool")
        VariablePool.resize(464, 416)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/图标.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VariablePool.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VariablePool)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(VariablePool)
        self.tableView.setAlternatingRowColors(False)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(VariablePool)
        QtCore.QMetaObject.connectSlotsByName(VariablePool)

    def retranslateUi(self, VariablePool):
        _translate = QtCore.QCoreApplication.translate
        VariablePool.setWindowTitle(_translate("VariablePool", "变量池"))
import images_rc
