# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '参数窗口.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Param(object):
    def setupUi(self, Param):
        Param.setObjectName("Param")
        Param.resize(264, 217)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/图标.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Param.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Param)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(Param)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(Param)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Param)
        QtCore.QMetaObject.connectSlotsByName(Param)

    def retranslateUi(self, Param):
        _translate = QtCore.QCoreApplication.translate
        Param.setWindowTitle(_translate("Param", "指令参数"))
        self.pushButton.setText(_translate("Param", "修改指令"))
import images_rc
