# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '图像选择.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageSelect(object):
    def setupUi(self, ImageSelect):
        ImageSelect.setObjectName("ImageSelect")
        ImageSelect.resize(356, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/按钮图标/窗体/res/图标.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImageSelect.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ImageSelect)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(ImageSelect)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(ImageSelect)
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(ImageSelect)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(ImageSelect)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(ImageSelect)
        QtCore.QMetaObject.connectSlotsByName(ImageSelect)

    def retranslateUi(self, ImageSelect):
        _translate = QtCore.QCoreApplication.translate
        ImageSelect.setWindowTitle(_translate("ImageSelect", "图像选择"))
        self.label.setText(_translate("ImageSelect", "图像预览区"))
        self.pushButton.setText(_translate("ImageSelect", "添加"))
        self.pushButton_2.setText(_translate("ImageSelect", "取消"))
import images_rc
